version: '2.1'
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /app/node_modules
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: 20qestions-db
